name: purrify
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  http: ^1.0.0
  spotify_sdk: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: 'ic_purrify'
  ios: true
  image_path: 'assets/icon/logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
